# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 723)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/running_stick.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.subject_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.subject_line_edit.setFont(font)
        self.subject_line_edit.setText("")
        self.subject_line_edit.setObjectName("subject_line_edit")
        self.verticalLayout_3.addWidget(self.subject_line_edit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plain_text_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        self.plain_text_radio_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plain_text_radio_button.sizePolicy().hasHeightForWidth())
        self.plain_text_radio_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plain_text_radio_button.setFont(font)
        self.plain_text_radio_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plain_text_radio_button.setAutoFillBackground(False)
        self.plain_text_radio_button.setChecked(True)
        self.plain_text_radio_button.setObjectName("plain_text_radio_button")
        self.horizontalLayout_2.addWidget(self.plain_text_radio_button)
        self.HTML_radio_button = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HTML_radio_button.sizePolicy().hasHeightForWidth())
        self.HTML_radio_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HTML_radio_button.setFont(font)
        self.HTML_radio_button.setCheckable(True)
        self.HTML_radio_button.setObjectName("HTML_radio_button")
        self.horizontalLayout_2.addWidget(self.HTML_radio_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.message_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.message_text_edit.setFont(font)
        self.message_text_edit.setTabChangesFocus(True)
        self.message_text_edit.setObjectName("message_text_edit")
        self.horizontalLayout.addWidget(self.message_text_edit)
        self.contacts_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.contacts_text_edit.setFont(font)
        self.contacts_text_edit.setTabChangesFocus(True)
        self.contacts_text_edit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.contacts_text_edit.setObjectName("contacts_text_edit")
        self.horizontalLayout.addWidget(self.contacts_text_edit)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.clear_console_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_console_button.sizePolicy().hasHeightForWidth())
        self.clear_console_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clear_console_button.setFont(font)
        self.clear_console_button.setObjectName("clear_console_button")
        self.verticalLayout.addWidget(self.clear_console_button)
        self.toggle_console_wrap_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggle_console_wrap_button.sizePolicy().hasHeightForWidth())
        self.toggle_console_wrap_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toggle_console_wrap_button.setFont(font)
        self.toggle_console_wrap_button.setObjectName("toggle_console_wrap_button")
        self.verticalLayout.addWidget(self.toggle_console_wrap_button)
        self.reset_progress_bar_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_progress_bar_button.sizePolicy().hasHeightForWidth())
        self.reset_progress_bar_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reset_progress_bar_button.setFont(font)
        self.reset_progress_bar_button.setObjectName("reset_progress_bar_button")
        self.verticalLayout.addWidget(self.reset_progress_bar_button)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_2.addWidget(self.progress_bar)
        self.console = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.console.setFont(font)
        self.console.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.console.setReadOnly(True)
        self.console.setObjectName("console")
        self.verticalLayout_2.addWidget(self.console)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toolBar.setFont(font)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_send = QtWidgets.QAction(MainWindow)
        self.action_send.setObjectName("action_send")
        self.action_authorize = QtWidgets.QAction(MainWindow)
        self.action_authorize.setObjectName("action_authorize")
        self.action_clear_fields = QtWidgets.QAction(MainWindow)
        self.action_clear_fields.setObjectName("action_clear_fields")
        self.action_toggle_theme = QtWidgets.QAction(MainWindow)
        self.action_toggle_theme.setObjectName("action_toggle_theme")
        self.toolBar.addAction(self.action_send)
        self.toolBar.addAction(self.action_authorize)
        self.toolBar.addAction(self.action_clear_fields)
        self.toolBar.addAction(self.action_toggle_theme)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyMailList"))
        self.subject_line_edit.setPlaceholderText(_translate("MainWindow", "Subject"))
        self.plain_text_radio_button.setText(_translate("MainWindow", "Plain Text"))
        self.HTML_radio_button.setText(_translate("MainWindow", "HTML"))
        self.message_text_edit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.message_text_edit.setPlaceholderText(_translate("MainWindow", "Message body (plain text or HTML)"))
        self.contacts_text_edit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.contacts_text_edit.setPlaceholderText(_translate("MainWindow", "Send the message to... (someone@example.com)"))
        self.clear_console_button.setText(_translate("MainWindow", "Clear Console"))
        self.toggle_console_wrap_button.setText(_translate("MainWindow", "Toggle Word Wrap"))
        self.reset_progress_bar_button.setText(_translate("MainWindow", "Reset Progress Bar"))
        self.console.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_send.setText(_translate("MainWindow", "Send"))
        self.action_send.setToolTip(_translate("MainWindow", "Send the message (Alt+S)"))
        self.action_send.setShortcut(_translate("MainWindow", "Alt+S"))
        self.action_authorize.setText(_translate("MainWindow", "Authorize"))
        self.action_authorize.setToolTip(_translate("MainWindow", "Force re-authorization (Alt+A)"))
        self.action_authorize.setShortcut(_translate("MainWindow", "Alt+A"))
        self.action_clear_fields.setText(_translate("MainWindow", "Clear"))
        self.action_clear_fields.setToolTip(_translate("MainWindow", "Clear form input fields (Alt+C)"))
        self.action_clear_fields.setShortcut(_translate("MainWindow", "Alt+C"))
        self.action_toggle_theme.setText(_translate("MainWindow", "Toggle Theme"))
        self.action_toggle_theme.setToolTip(_translate("MainWindow", "Toggle between light and dark theme (Alt+T)"))
        self.action_toggle_theme.setShortcut(_translate("MainWindow", "Alt+T"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

